# Generated by Django 2.2.6 on 2019-12-16 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('mentor', models.CharField(max_length=100)),
                ('day_f', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Courses_Single',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, choices=[('B', 'Boxing'), ('C', 'Cycling'), ('Y', 'Yoga'), ('M', 'Meditation'), ('G', 'Gym-Fitness')], max_length=1, null=True)),
                ('mentor', models.CharField(max_length=100)),
                ('day_f', models.DateTimeField(default=datetime.date.today)),
                ('day_t', models.DateTimeField(default=datetime.date.today)),
                ('student', models.IntegerField()),
                ('price', models.FloatField()),
                ('shift', models.CharField(blank=True, choices=[('M', 'Morning'), ('E', 'Evening')], max_length=1, null=True)),
                ('timing', models.FloatField()),
                ('calo', models.FloatField()),
                ('desc', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
