# Generated by Django 2.2.6 on 2019-12-04 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(max_length=500)),
                ('intro', models.TextField(max_length=500)),
                ('photo', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Achivement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_a', models.CharField(max_length=30)),
                ('a_date', models.DateField(default=datetime.date.today)),
                ('desc', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('speci', models.CharField(max_length=30)),
                ('colleg', models.CharField(max_length=30)),
                ('s_date', models.DateField(default=datetime.date.today)),
                ('e_date', models.DateField(default=datetime.date.today)),
                ('marks', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_o', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('type_j', models.CharField(blank=True, choices=[('I', 'Internship'), ('F', 'Full Time'), ('P', 'Part Time')], max_length=1, null=True)),
                ('s_date', models.DateField(default=datetime.date.today)),
                ('e_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
